name: LinuxEnv
channels:
  - conda-forge
  - defaults
dependencies:
  - pip
  - python=3.12
  - yt-dlp
  - scikit-learn
  - tqdm
  - opencv
  - h5py
  - fvcore
  - iopath
  - pip:
    - pandas
    - torch
    - torchvision 

